# This is a basic workflow to help you get started with Actions

name: Deploy to GitHub Pages
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: yarn install
    - name: Generate production build
      run: yarn build
    - name: Deploy to branch for GH-Page
      run: |
        git config user.email "github-action@users.noreply.github.com" 
        git config user.name "GitHub Action"
        cd dist
        git init
        git add -A
        git commit -m 'deploy'
        git push -f git@github.com:UweStolz/gifgif.git master:gh-pages
      env:
        CI: true

